name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: Hello World
      uses: jairogomz/hello-world-javascript-action-by-jairo@v1.0.1
      with:
        who-to-greet: 'Andy Teh CaCa'

    - name: Do the dotnet build
      run: |
        echo 'doing dotnet build'
        dotnet build
        echo 'dotnet build done'

    - name: Do the dotnet test
      run: |
        echo 'doing dotnet test'
        dotnet test
        echo 'dotnet test done'